title: Anahita Azam
description: 
**Economist | Computational Social Scientist | Data Enthusiast**  
Toronto, Canada | [Email Me](mailto:ana.azam@alumni.utoronto.ca) | [GitHub](https://github.com/anaazam) | [LinkedIn](https://www.linkedin.com/in/anahita-azam/)  

theme: jekyll-theme-slate
